[mgr]
prepend_keymap = [
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go to ~/Downloads" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "Go to ~/.config" },
  { on = [ "g", "r" ], run = "cd ~/src", desc = "Go to ~/src" },
  { on = "l", run = "enter", desc = "Enter directory" },
  { on = "h", run = "leave", desc = "Leave directory" }
]

