"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 800
scan_timeout = 30

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold yellow)"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold blue"
read_only = " ro"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "bold mauve"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"

[cmd_duration]
min_time = 1500
format = "[${duration}](dimmed white)"

[fill]
symbol = " "

[package]
disabled = true

